#include "window.h"
#include "emailview.h"
#include "attachments.h"
#include "theme.h"
#include "mime.h"
#include "gmailactions.h"
#include "mailsync.h"
#include <QPdfDocument>
#include <QPdfWriter>
#include <QBuffer>
#include <QWebEngineView>
#include <QWebEnginePage>
#include <QWebEngineSettings>
#include <QtTest>
#include <QUrlQuery>
#include <QDesktopServices>
#include <QScopeGuard>
#include <QtWidgets>
static QStringList parserWarnings;
static void captureParserWarning(QtMsgType type,const QMessageLogContext&,const QString&message){if(type==QtWarningMsg)parserWarnings.append(message);}
class UrlCapture:public QObject{Q_OBJECT
public:QUrl url;int calls=0;
public slots:void open(QUrl value){url=value;++calls;}
};
class FixtureGoogle:public GoogleClient{
public:
 using GoogleClient::GoogleClient;
 QList<QJsonObject> calls;std::function<void(QString,QList<QPair<QString,QString>>,Done)> onGet;std::function<void(QString,QString,QJsonObject,Done)> onMutate;
 void get(const QString&p,const QList<QPair<QString,QString>>&q,Done d)override{QTimer::singleShot(0,this,[this,p,q,d]{if(onGet)onGet(p,q,d);else d({},"Unexpected fixture GET: "+p);});}
 void mutate(const QString&m,const QString&p,const QJsonObject&b,Done d)override{calls.append(QJsonObject{{"method",m},{"path",p},{"body",b}});QTimer::singleShot(0,this,[this,m,p,b,d]{if(onMutate)onMutate(m,p,b,d);else d({},{});});}
};
class NativeTests:public QObject{
Q_OBJECT
private slots:
 void keyringTransport(){QTemporaryDir dir;QString helper=dir.path()+"/secret-tool",file=dir.path()+"/fixture";QFile script(helper);QVERIFY(script.open(QIODevice::WriteOnly));script.write(R"(#!/bin/sh
printf '%s\n' "$@" > "$OMADASH_KEYRING_FIXTURE.args"
case "$1" in
store) cat > "$OMADASH_KEYRING_FIXTURE" ;;
lookup) cat "$OMADASH_KEYRING_FIXTURE" ;;
clear) rm -f "$OMADASH_KEYRING_FIXTURE" ;;
esac
)");script.close();QVERIFY(script.setPermissions(QFile::ReadOwner|QFile::WriteOwner|QFile::ExeOwner));auto path=qgetenv("PATH"),old=qgetenv("OMADASH_KEYRING_FIXTURE");auto cleanup=qScopeGuard([&]{qputenv("PATH",path);if(old.isNull())qunsetenv("OMADASH_KEYRING_FIXTURE");else qputenv("OMADASH_KEYRING_FIXTURE",old);});qputenv("PATH",dir.path().toUtf8()+":"+path);qputenv("OMADASH_KEYRING_FIXTURE",file.toUtf8());Keyring ring;bool done=false;ring.write("fixture@example.org","dummy-token-for-test",[&](QByteArray,QString e){QVERIFY(e.isEmpty());done=true;});QTRY_VERIFY(done);QFile args(file+".args");QVERIFY(args.open(QIODevice::ReadOnly));QVERIFY(!args.readAll().contains("dummy-token-for-test"));done=false;ring.read("fixture@example.org",[&](QByteArray value,QString e){QVERIFY(e.isEmpty());QCOMPARE(value,QByteArray("dummy-token-for-test"));done=true;});QTRY_VERIFY(done);done=false;ring.remove("fixture@example.org",[&](QByteArray,QString e){QVERIFY(e.isEmpty());done=true;});QTRY_VERIFY(done);QVERIFY(!QFile::exists(file));}
 void liveComposeWorkflow(){OmadashWindow w(false);auto*c=new FixtureGoogle(&w);c->restoreCredentials(R"({"refresh_token":"fixture","modify":true})");auto thread=w.store.threads.first().toObject();thread["account"]="one@example.org";thread["id"]="live-thread";w.registerAccount("one@example.org",c,false);w.store.threads=QJsonArray{thread};w.show();w.openThread(0);w.selectMessage(0);w.compose("reply-all");auto id=w.activeDraft();QVERIFY(!id.isEmpty());QCOMPARE(w.store.drafts[id].toObject()["threadId"].toString(),QString("live-thread"));QCOMPARE(w.store.drafts[id].toObject()["sourceMessage"].toInt(),0);QVERIFY(!w.fromEdit->isEnabled());w.bodyEdit->setPlainText("Selected message reply");w.persistDraft();QCOMPARE(w.cache->drafts()[id].toObject()["body"].toString(),QString("Selected message reply"));w.openLiveDraft(id);QCOMPARE(w.pages->currentIndex(),2);QCOMPARE(w.bodyEdit->toPlainText(),QString("Selected message reply"));QVERIFY(w.findChild<QPushButton*>("sendButton")->text().startsWith("Send"));if(qEnvironmentVariableIsSet("OMADASH_CAPTURE_ARTIFACTS")){QTest::qWait(100);w.grab().save(QCoreApplication::applicationDirPath()+"/../compose-preview-06.png");}}
 void cacheRestartAndIsolation(){QTemporaryDir dir;QString path=dir.path()+"/mail.sqlite";{LocalCache c(path);QVERIFY2(c.ready(),qPrintable(c.error));c.putThread("one",QJsonObject{{"id","same"},{"subject","Quarterly unicorn report"},{"date","2026-09-13"}});c.putThread("two",QJsonObject{{"id","same"},{"subject","Private other account"}});QVERIFY(c.putDraft("draft",QJsonObject{{"account","one"},{"body","Keep after restart"},{"attachments",QJsonArray{QJsonObject{{"name","test.txt"},{"data","aGVsbG8="}}}}}));c.setMeta("one","remember","1");QCOMPARE(c.search("one","unicorn").size(),1);QVERIFY(c.search("two","unicorn").isEmpty());}LocalCache c(path);QCOMPARE(c.threads("one").size(),1);QCOMPARE(c.drafts()["draft"].toObject()["body"].toString(),QString("Keep after restart"));QCOMPARE(c.accounts(),QStringList{"one"});c.forget("one");QVERIFY(c.threads("one").isEmpty());QVERIFY(c.drafts().contains("draft"));QCOMPARE(c.threads("two").size(),1);auto perms=QFile::permissions(path);QVERIFY(!(perms&QFile::ReadOther));QVERIFY(!(perms&QFile::ReadGroup));}
 void mimeSafetyAndAttachment(){QString error;QJsonObject d{{"to","recipient@example.org"},{"cc","copy@example.org"},{"bcc","hidden@example.org"},{"subject","Résumé ✔"},{"body","Hello\nworld"},{"sourceId","<original@example.org>"},{"mode","reply"},{"attachments",QJsonArray{QJsonObject{{"name","résumé.txt"},{"mime","text/plain"},{"data","YmluYXJ5AA=="}}}}};auto raw=Mime::message(d,"owner@example.org",&error);QVERIFY2(error.isEmpty(),qPrintable(error));QVERIFY(raw.contains("From: owner@example.org"));QVERIFY(raw.contains("In-Reply-To: <original@example.org>"));QVERIFY(raw.contains("References: <original@example.org>"));QVERIFY(raw.contains("multipart/mixed"));QVERIFY(raw.contains("YmluYXJ5AA=="));QVERIFY(raw.contains("filename*=UTF-8''r%C3%A9sum%C3%A9.txt"));d["subject"]="Subject\r\nBcc: injected@example.org";QVERIFY(Mime::message(d,"owner@example.org",&error).isEmpty());QVERIFY(!error.isEmpty());}
 void triageExactUndo(){FixtureGoogle c;QJsonArray messages{QJsonObject{{"id","m1"},{"labelIds",QJsonArray{"INBOX","UNREAD","IMPORTANT"}}},QJsonObject{{"id","m2"},{"labelIds",QJsonArray{"INBOX"}}}};c.onGet=[messages](QString,QList<QPair<QString,QString>>,GoogleClient::Done done){done(QJsonObject{{"messages",messages}},{});};bool done=false;QJsonObject record;GmailActions::apply(&c,"t","unread",[&](QJsonObject result,QString error){QVERIFY(error.isEmpty());record=result["undo"].toObject();done=true;});QTRY_VERIFY(done);QCOMPARE(c.calls.first()["body"].toObject()["addLabelIds"].toArray(),QJsonArray{"UNREAD"});done=false;GmailActions::undo(&c,record,[&](QJsonObject,QString e){QVERIFY(e.isEmpty());done=true;});QTRY_VERIFY(done);QCOMPARE(c.calls.size(),3);QCOMPARE(c.calls[1]["body"].toObject()["addLabelIds"].toArray(),QJsonArray{"UNREAD"});QCOMPARE(c.calls[2]["body"].toObject()["removeLabelIds"].toArray(),QJsonArray{"UNREAD"});}
 void syncCheckpoint(){LocalCache cache(":memory:");FixtureGoogle c;cache.setMeta("one","baseline","complete");cache.setMeta("one","history","10");c.onGet=[](QString path,QList<QPair<QString,QString>>,GoogleClient::Done done){if(path.endsWith("history"))done(QJsonObject{{"historyId","11"},{"history",QJsonArray{QJsonObject{{"messages",QJsonArray{QJsonObject{{"threadId","t"}}}}}}}},{});else done(QJsonObject{{"_httpStatus",503}},"Offline");};MailSync sync(&c,&cache,"one");sync.refresh();QTest::qWait(30);QCOMPARE(cache.meta("one","history"),QString("10"));c.onGet=[](QString path,QList<QPair<QString,QString>>,GoogleClient::Done done){if(path.endsWith("history"))done(QJsonObject{{"historyId","11"}},{});else done({},"Unexpected");};sync.refresh();QTRY_COMPARE(cache.meta("one","history"),QString("11"));}
 void sendUsesDraftOwner(){OmadashWindow w(false);auto*c=new FixtureGoogle(&w);c->restoreCredentials(R"({"refresh_token":"fixture","modify":true})");w.registerAccount("one@example.org",c,false);QString id="test-send";w.store.drafts[id]=QJsonObject{{"account","one@example.org"},{"to","recipient@example.org"},{"subject","Fixture"},{"body","Test only"}};c->onMutate=[](QString,QString path,QJsonObject,GoogleClient::Done done){done(path.endsWith("/send")?QJsonObject{{"id","sent"},{"threadId","t"}}:QJsonObject{{"id","gmail-draft"}},{});};w.syncDraft(id,true);QTRY_VERIFY(!w.store.drafts.contains(id));QCOMPARE(c->calls.size(),2);QVERIFY(c->calls[0]["path"].toString().endsWith("/drafts"));QVERIFY(c->calls[1]["path"].toString().endsWith("/drafts/send"));auto encoded=c->calls[0]["body"].toObject()["message"].toObject()["raw"].toString().toLatin1();QVERIFY(QByteArray::fromBase64(encoded,QByteArray::Base64UrlEncoding).contains("From: one@example.org"));}
 void uncertainSendNotRetried(){OmadashWindow w(false);auto*c=new FixtureGoogle(&w);c->restoreCredentials(R"({"refresh_token":"fixture","modify":true})");w.registerAccount("one@example.org",c,false);w.store.drafts["d"]=QJsonObject{{"account","one@example.org"},{"to","recipient@example.org"},{"body","Keep"}};c->onMutate=[](QString,QString path,QJsonObject,GoogleClient::Done done){if(path.endsWith("/send"))done(QJsonObject{{"_uncertain",true}},"Timeout");else done(QJsonObject{{"id","saved"}},{});};w.syncDraft("d",true);QTRY_VERIFY(!w.draftJobs.contains("d"));QVERIFY(w.store.drafts["d"].toObject()["uncertain"].toBool());QVERIFY(w.cache->drafts().contains("d"));w.syncDraft("d",true);QTest::qWait(20);QCOMPARE(c->calls.size(),2);}
 void accountImagePreferences(){OmadashWindow w(false);w.setAccountImages("one@example.org",true);QVERIFY(w.externalImages.value("one@example.org"));QVERIFY(!w.externalImages.value("two@example.org",false));auto t=w.store.threads[0].toObject();t["account"]="one@example.org";auto messages=t["messages"].toArray();auto m=messages.last().toObject();m["html"]="<p>Formatted content</p>";messages[messages.size()-1]=m;t["messages"]=messages;w.store.threads[0]=t;w.account="one@example.org";w.openThread(0);auto*reader=w.findChild<EmailView*>();QVERIFY(reader);QVERIFY(reader->property("externalImagesEnabled").toBool());QVERIFY(reader->findChildren<QPushButton*>().isEmpty());w.setAccountImages("one@example.org",false);QCoreApplication::sendPostedEvents(nullptr,QEvent::DeferredDelete);reader=w.findChild<EmailView*>();QVERIFY(reader);QVERIFY(!reader->property("externalImagesEnabled").toBool());QVERIFY(!w.externalImages.value("two@example.org",false));}
 void malformedEmailStyles(){QString html="<style>p {font-size:0px}</style><div color='1' style='color:1;font-size:0px'><font color='1'>Hello &amp; welcome</font><p>Second line</p><a href='https://example.com'>Read more</a></div>";auto payload=QJsonObject{{"mimeType","text/html"},{"body",QJsonObject{{"data",QString::fromLatin1(html.toUtf8().toBase64(QByteArray::Base64UrlEncoding))}}}};parserWarnings.clear();auto previous=qInstallMessageHandler(captureParserWarning);auto t=GoogleClient::normalizeThread(QJsonObject{{"messages",QJsonArray{QJsonObject{{"payload",payload},{"internalDate","1789301700000"}}}}},"fixture");qInstallMessageHandler(previous);auto message=t["messages"].toArray().first().toObject();QVERIFY2(message["body"].toString().contains("Hello & welcome"),qPrintable(message["body"].toString()+parserWarnings.join("\n")));QVERIFY(message["body"].toString().contains("Second line"));QVERIFY(message["body"].toString().contains("Read more"));QCOMPARE(message["html"].toString(),html);QVERIFY2(parserWarnings.isEmpty(),qPrintable(parserWarnings.join("\n")));}
 void responsiveReader(){OmadashWindow w(false);auto t=w.store.threads[0].toObject();auto messages=t["messages"].toArray();auto m=messages.last().toObject();m["html"]="<div style='width:1200px;max-width:1200px'><table width='1200'><tr><td>"+QString("Long readable content ").repeated(100)+"</td></tr></table></div>";messages[messages.size()-1]=m;t["messages"]=messages;w.store.threads[0]=t;w.resize(900,800);w.show();w.openThread(0);auto*web=w.findChild<QWebEngineView*>("htmlEmailBody");QVERIFY(web);QSignalSpy ready(web,&QWebEngineView::loadFinished);QVERIFY(ready.wait(10000));int narrow=web->width();QVERIFY(narrow>700);QTRY_VERIFY(web->page()->contentsSize().width()<=web->width()+2);w.resize(1600,800);QTRY_VERIFY(web->width()>narrow+600);w.resize(900,800);QTRY_COMPARE(web->width(),narrow);QTRY_VERIFY(web->page()->contentsSize().width()<=web->width()+2);QCOMPARE(w.threadScroll->horizontalScrollBar()->maximum(),0);w.back();int listWidth=w.inbox->viewport()->width();w.resize(1600,800);QTRY_VERIFY(w.inbox->viewport()->width()>listWidth+600);}
 void themeFiles(){QTemporaryDir dir;auto fallback=MailTheme::load(dir.path());QVERIFY(!fallback.loaded);QFile f(dir.path()+"/colors.toml");QVERIFY(f.open(QIODevice::WriteOnly));f.write("background = \"#121212\"\nforeground = \"#eeeeee\"\naccent = \"#aabbcc\"\ncolor4 = \"#5599ff\"\n");f.close();auto theme=MailTheme::load(dir.path());QVERIFY(theme.loaded);QCOMPARE(theme.background,QColor("#121212"));QCOMPARE(theme.accent,QColor("#aabbcc"));QCOMPARE(theme.blue,QColor("#5599ff"));QVERIFY(f.remove());QFile legacy(dir.path()+"/alacritty.toml");QVERIFY(legacy.open(QIODevice::WriteOnly));legacy.write("[colors.primary]\nbackground = '#ffffff'\nforeground = '#222222'\n[colors.normal]\nblue = '#5577cc'\n");legacy.close();theme=MailTheme::load(dir.path());QVERIFY(theme.loaded);QCOMPARE(theme.accent,QColor("#5577cc"));}
 void signInRecovery(){UrlCapture capture;QDesktopServices::setUrlHandler("https",&capture,"open");struct Reset{~Reset(){QDesktopServices::unsetUrlHandler("https");}}reset;OmadashWindow w(false);auto*c=w.makeGoogleClient();QString error;QVERIFY(c->configure(R"({"installed":{"client_id":"fixture.apps.googleusercontent.com"}})",&error));w.pendingGoogle=c;c->authorize();QCOMPARE(capture.calls,1);QVERIFY(!w.signInControls->isHidden());QVERIFY(!c->signInUrl().isEmpty());QUrlQuery query(capture.url);QCOMPARE(query.queryItemValue("code_challenge_method"),QString("S256"));QVERIFY(!query.queryItemValue("scope").contains("gmail.modify"));auto state=query.queryItemValue("state");c->authorize();QCOMPARE(capture.calls,1);for(auto*b:w.signInControls->findChildren<QPushButton*>())if(b->text()=="Copy sign-in link")b->click();QCOMPARE(QApplication::clipboard()->text(),capture.url.toString(QUrl::FullyEncoded));for(auto*b:w.signInControls->findChildren<QPushButton*>())if(b->text()=="Cancel")b->click();QVERIFY(!w.pendingGoogle);QVERIFY(c->signInUrl().isEmpty());QVERIFY(w.signInControls->isHidden());c->authorize(true,"one@example.org");QCOMPARE(capture.calls,2);QUrlQuery again(capture.url);QVERIFY(again.queryItemValue("state")!=state);QVERIFY(again.queryItemValue("scope").contains("gmail.modify"));QCOMPARE(again.queryItemValue("login_hint"),QString("one@example.org"));c->disconnectAccount();QApplication::clipboard()->clear();}
 void unreadPermissionKeepsReader(){OmadashWindow w(false);auto threads=w.store.threads;w.registerAccount("one@example.org",w.makeGoogleClient(),false);auto t=threads.first().toObject();t["account"]="one@example.org";t["unread"]=false;w.store.threads=QJsonArray{t};w.openThread(0);w.markUnread();QCOMPARE(w.pages->currentIndex(),1);QVERIFY(!w.store.threads[0].toObject()["unread"].toBool());QVERIFY(!w.commandPanel->isHidden());}

 void pdfAttachment(){QByteArray bytes;QBuffer buffer(&bytes);QVERIFY(buffer.open(QIODevice::WriteOnly));{QPdfWriter writer(&buffer);QPainter painter(&writer);painter.drawText(200,300,"Omadash attachment preview");}OmadashWindow w(false);w.show();w.openThread(0);w.showAttachment("Project brief.pdf","application/pdf",bytes);auto*doc=w.attachmentPage->findChild<QPdfDocument*>();QVERIFY(doc);QTRY_COMPARE_WITH_TIMEOUT(doc->status(),QPdfDocument::Status::Ready,5000);QCOMPARE(doc->pageCount(),1);QCOMPARE(w.pages->currentWidget(),w.attachmentPage);if(qEnvironmentVariableIsSet("OMADASH_CAPTURE_ARTIFACTS")){QTest::qWait(250);w.grab().save(QCoreApplication::applicationDirPath()+"/../attachment-preview.png");}w.back();QCOMPARE(w.pages->currentIndex(),1);}

 void accountIsolation(){OmadashWindow w(false);auto samples=w.store.threads;auto*a=w.makeGoogleClient();w.registerAccount("one@example.org",a,false);w.store.threads=QJsonArray{QJsonObject{{"id","same-id"},{"account","one@example.org"},{"subject","One"},{"labels",QJsonArray{"important"}}}};w.pageToken="page-one";w.query="from:one";auto*b=w.makeGoogleClient();w.registerAccount("two@example.org",b,false);QVERIFY(w.store.threads.isEmpty());QCOMPARE(w.google,b);w.store.threads=QJsonArray{QJsonObject{{"id","same-id"},{"account","two@example.org"},{"subject","Two"},{"labels",QJsonArray{"important"}}}};w.pageToken="page-two";w.switchAccount("one@example.org",false);QCOMPARE(w.google,a);QCOMPARE(w.store.threads.first().toObject()["subject"].toString(),QString("One"));QCOMPARE(w.pageToken,QString("page-one"));QCOMPARE(w.query,QString("from:one"));w.switchAccount("two@example.org",false);QCOMPARE(w.pageToken,QString("page-two"));QCOMPARE(w.store.threads.first().toObject()["subject"].toString(),QString("Two"));w.leaveGoogle();QCOMPARE(w.account,QString("one@example.org"));QCOMPARE(w.sessions.size(),1);w.leaveGoogle();QVERIFY(!w.live);QCOMPARE(w.store.threads,samples);}
 void duplicateAccount(){OmadashWindow w(false);w.registerAccount("one@example.org",w.makeGoogleClient(),false);auto*replacement=w.makeGoogleClient();w.registerAccount("one@example.org",replacement,false);QCOMPARE(w.sessions.size(),1);QCOMPARE(w.accountOrder.size(),1);QCOMPARE(w.store.accounts.size(),1);QCOMPARE(w.google,replacement);}
 void attachmentPartsAndSave(){QJsonObject p{{"mimeType","multipart/mixed"},{"parts",QJsonArray{QJsonObject{{"mimeType","text/plain"},{"body",QJsonObject{{"data","dGV4dA"}}}},QJsonObject{{"filename","../invoice.pdf"},{"mimeType","application/pdf"},{"body",QJsonObject{{"attachmentId","file-id"},{"size",99}}}}}}};auto a=Attachments::collect(p);QCOMPARE(a.size(),1);QCOMPARE(a.first().toObject()["id"].toString(),QString("file-id"));QCOMPARE(Attachments::safeName("../invoice.pdf"),QString("invoice.pdf"));QCOMPARE(Attachments::safeName("C:\\folder\\file.txt"),QString("file.txt"));QCOMPARE(Attachments::safeName(".."),QString("attachment"));QTemporaryDir dir;QByteArray bytes("\0binary\xff",8);QString error;QVERIFY(Attachments::save(dir.path()+"/file",bytes,&error));QFile f(dir.path()+"/file");QVERIFY(f.open(QIODevice::ReadOnly));QCOMPARE(f.readAll(),bytes);QVERIFY(!Attachments::save(dir.path()+"/missing/file",bytes,&error));}
 void attachmentWorkspace(){OmadashWindow w(false);w.show();w.openThread(0);w.showAttachment("notes.html","text/html","<script>never run</script>");QCOMPARE(w.pages->currentWidget(),w.attachmentPage);auto*text=w.attachmentPage->findChild<QPlainTextEdit*>();QVERIFY(text);QCOMPARE(text->toPlainText(),QString("<script>never run</script>"));w.back();QCOMPARE(w.pages->currentIndex(),1);}
 void readerUnread(){OmadashWindow w(false);w.openThread(0);w.markUnread();QCOMPARE(w.pages->currentIndex(),0);QVERIFY(w.store.threads[0].toObject()["unread"].toBool());w.openThread(0);w.markUnread();QVERIFY(w.store.threads[0].toObject()["unread"].toBool());}
 void deniedUnread(){GoogleClient c;bool called=false;c.setThreadUnread("thread",true,[&](QJsonObject,QString error){called=true;QVERIFY(!error.isEmpty());});QVERIFY(called);QVERIFY(!c.canModify());}

 void renderHtml(){EmailView reader("<h1>Readable heading</h1><table><tr><td>Styled table</td></tr></table><script>document.body.innerText='SCRIPT EXECUTED'</script>");reader.resize(700,600);reader.show();auto*web=reader.findChild<QWebEngineView*>();QVERIFY(web);QVERIFY(!web->settings()->testAttribute(QWebEngineSettings::JavascriptEnabled));QSignalSpy ready(web,&QWebEngineView::loadFinished);QVERIFY(ready.wait(15000));QVERIFY(ready.last().first().toBool());QString text;bool done=false;web->page()->toPlainText([&](const QString&value){text=value;done=true;});QTRY_VERIFY_WITH_TIMEOUT(done,5000);QVERIFY(text.contains("Readable heading"));QVERIFY(text.contains("Styled table"));QVERIFY(!text.contains("SCRIPT EXECUTED"));}

 void htmlPolicy(){auto doc=EmailView::document("<table><tr><td>Designed email</td></tr></table>",false);QVERIFY(doc.contains("<table>"));QVERIFY(doc.contains("script-src 'none'"));QVERIFY(doc.contains("img-src data:;"));QVERIFY(EmailView::document("",true).contains("img-src data: https: http:"));QVERIFY(!EmailView::externalLink(QUrl("file:///etc/passwd")));QVERIFY(!EmailView::externalLink(QUrl("javascript:alert(1)")));QVERIFY(EmailView::externalLink(QUrl("https://example.com")));}
 void htmlMime(){auto payload=QJsonObject{{"mimeType","multipart/alternative"},{"parts",QJsonArray{QJsonObject{{"mimeType","text/plain"},{"body",QJsonObject{{"data",QString::fromLatin1(QByteArray("Plain").toBase64())}}}},QJsonObject{{"mimeType","text/html"},{"body",QJsonObject{{"data",QString::fromLatin1(QByteArray("<h1>Designed</h1>").toBase64())}}}}}}};auto t=GoogleClient::normalizeThread(QJsonObject{{"messages",QJsonArray{QJsonObject{{"payload",payload},{"internalDate","1789301700000"}}}}},"google");auto m=t["messages"].toArray().first().toObject();QCOMPARE(m["body"].toString(),QString("Plain"));QCOMPARE(m["html"].toString(),QString("<h1>Designed</h1>"));}

 void history(){MailStore s(false);QVERIFY(s.threads.size()>10);QVERIFY(!s.visible("all","important","search","before:2022-01-01").isEmpty());}
 void selectedReply(){MailStore s(false);auto d=s.replyDraft(0,0,"reply-all");QCOMPARE(d["sourceMessage"].toInt(),0);QVERIFY(d["bcc"].toString().isEmpty());}
 void keyboard(){OmadashWindow w(false);w.show();QTest::qWait(50);auto*l=w.findChild<QListWidget*>("conversationList");QVERIFY(l->count()>0);l->setFocus();QTest::keyClick(l,Qt::Key_Return);QCOMPARE(w.findChild<QStackedWidget*>("workspace")->currentIndex(),1);w.selectMessage(0);auto*card=w.findChild<QFrame*>("messageCard");QVERIFY(card);QTest::keyClick(card,Qt::Key_Return);QCOMPARE(w.store.drafts[w.activeDraft()].toObject()["sourceMessage"].toInt(),0);QVERIFY(w.findChild<QTextEdit*>("draftBody"));}
 void preserveDraft(){OmadashWindow w(false);w.show();QTest::qWait(50);w.compose();auto*body=w.findChild<QTextEdit*>("draftBody");body->setPlainText("Keep this draft");w.search();QCOMPARE(w.findChild<QStackedWidget*>("workspace")->currentIndex(),0);w.back();QCOMPARE(w.store.drafts[w.activeDraft()].toObject()["body"].toString(),QString("Keep this draft"));w.toggleCalendar();auto*c=w.findChild<QFrame*>("calendarPanel");QVERIFY(c->isVisible());QCOMPARE(c->window(),&w);}
 void pkce(){QCOMPARE(GoogleClient::challenge("dBjftJeZ4CVP-mB92K27uhbUJU1p1r_wW1gFWFOEjXk"),QString("E9Melhoa2OwvFrEMTJguCHaoeK1t8URWbuGJSstw-cM"));QCOMPARE(GoogleClient::scopes().size(),2);for(auto s:GoogleClient::scopes())QVERIFY(s.endsWith("readonly"));}
 void callbackValidation(){QUrl result;QVERIFY(GoogleClient::validCallback("GET /oauth/callback?state=expected&code=code HTTP/1.1\r\n\r\n","expected",&result));QVERIFY(!GoogleClient::validCallback("GET /oauth/callback?state=wrong&code=code HTTP/1.1\r\n\r\n","expected",&result));QVERIFY(!GoogleClient::validCallback("GET /oauth/callback?state=expected&state=wrong HTTP/1.1\r\n\r\n","expected",&result));QVERIFY(!GoogleClient::validCallback("POST /oauth/callback?state=expected HTTP/1.1\r\n\r\n","expected",&result));QVERIFY(!GoogleClient::validCallback("GET /wrong?state=expected HTTP/1.1\r\n\r\n","expected",&result));}
 void clientConfig(){QString error;QVERIFY(GoogleClient::parseClient(R"({"web":{"client_id":"abc.apps.googleusercontent.com"}})",&error).isEmpty());QVERIFY(!error.isEmpty());QVERIFY(!GoogleClient::parseClient(R"({"installed":{"client_id":"abc.apps.googleusercontent.com"}})",&error).isEmpty());QVERIFY(error.isEmpty());}
 void gmailMapping(){QJsonArray headers{QJsonObject{{"name","From"},{"value","Sender <sender@example.org>"}},QJsonObject{{"name","To"},{"value","\"Doe, Jane\" <jane@example.org>, other@example.org"}},QJsonObject{{"name","Subject"},{"value","A real thread"}},QJsonObject{{"name","Date"},{"value","Sun, 13 Sep 2026 08:15:00 -0400"}}};auto encoded=QString::fromLatin1(QByteArray("Hello from plain mail").toBase64(QByteArray::Base64UrlEncoding));QJsonObject message{{"id","m1"},{"internalDate","1789301700000"},{"labelIds",QJsonArray{"INBOX","UNREAD","IMPORTANT"}},{"payload",QJsonObject{{"mimeType","text/plain"},{"headers",headers},{"body",QJsonObject{{"data",encoded}}}}}};auto thread=GoogleClient::normalizeThread(QJsonObject{{"id","t1"},{"snippet","Hello &amp; welcome"},{"messages",QJsonArray{message}}},"google");QCOMPARE(thread["subject"].toString(),QString("A real thread"));QCOMPARE(thread["account"].toString(),QString("google"));QVERIFY(thread["unread"].toBool());QVERIFY(!thread["archived"].toBool());auto m=thread["messages"].toArray().first().toObject();QCOMPARE(m["body"].toString(),QString("Hello from plain mail"));QCOMPARE(m["to"].toArray().size(),2);QVERIFY(m["bcc"].isNull());QCOMPARE(m["fromEmail"].toString(),QString("sender@example.org"));QVERIFY(m["date"].toString().contains("-04:00"));MailStore store(false);QCOMPARE(store.matchingSplit(thread),QString("important"));}
 void readOnlyGuards(){OmadashWindow w(false);w.live=true;w.store.setSessionOnly(true);auto original=w.store.threads;w.compose();QVERIFY(w.activeDraft().isEmpty());w.change("archive");QCOMPARE(w.store.threads,original);w.openThread(0);QCOMPARE(w.store.threads,original);w.save();}

};
QTEST_MAIN(NativeTests)
#include "test_native.moc"
