#include "google.h"
#include "attachments.h"
#include <QJsonDocument>
#include <QNetworkReply>
#include <QNetworkRequest>
#include <QTcpSocket>
#include <QUrlQuery>
#include <QDesktopServices>
#include <QCryptographicHash>
#include <QRandomGenerator>
#include <QRegularExpression>
#include <QTextDocument>
#include <algorithm>
#include <QTimeZone>
namespace {
QString randomString(){QByteArray data;for(int i=0;i<8;++i){quint32 n=QRandomGenerator::system()->generate();data.append(reinterpret_cast<const char*>(&n),sizeof(n));}return data.toBase64(QByteArray::Base64UrlEncoding|QByteArray::OmitTrailingEquals);}
QString header(const QJsonObject&p,const QString&name){for(auto h:p["headers"].toArray()){auto o=h.toObject();if(o["name"].toString().compare(name,Qt::CaseInsensitive)==0)return o["value"].toString();}return {};}
QString email(QString value){auto m=QRegularExpression("<([^<>]+)>").match(value);return m.hasMatch()?m.captured(1).trimmed():value.trimmed();}
QJsonArray addresses(const QString&text){QJsonArray a;auto it=QRegularExpression(R"((?:[^,"<]|"[^"]*"|<[^>]*>)+)").globalMatch(text);while(it.hasNext()){auto s=email(it.next().captured());if(!s.isEmpty())a.append(s);}return a;}
QString body(const QJsonObject&p,const QString&type){if(!p["filename"].toString().isEmpty())return {};if(p["mimeType"].toString()==type)return QString::fromUtf8(QByteArray::fromBase64(p["body"].toObject()["data"].toString().toLatin1(),QByteArray::Base64UrlEncoding));QStringList pieces;for(auto v:p["parts"].toArray()){auto text=body(v.toObject(),type);if(!text.isEmpty())pieces<<text;}return pieces.join("\n");}
void assets(const QJsonObject&p,QJsonArray&out){QString mime=p["mimeType"].toString();bool image=QStringList{"image/png","image/jpeg","image/gif","image/webp"}.contains(mime);QString cid=header(p,"Content-ID");cid.remove('<');cid.remove('>');bool text=(mime=="text/html"||mime=="text/plain")&&p["filename"].toString().isEmpty();auto b=p["body"].toObject();if((image&&!cid.isEmpty())||text){if(!b["attachmentId"].toString().isEmpty()||(image&&!b["data"].toString().isEmpty()))out.append(QJsonObject{{"mime",mime},{"cid",cid},{"attachmentId",b["attachmentId"]},{"data",b["data"]},{"size",b["size"]}});}for(auto part:p["parts"].toArray())assets(part.toObject(),out);}
QString plain(const QString&html){
 // This is a text projection, not the formatted reader. Ignore sender styling
 // before passing content to Qt's limited rich-text parser.
 QString text=html;
 text.remove(QRegularExpression("<!--.*?-->",QRegularExpression::DotMatchesEverythingOption));
 text.remove(QRegularExpression(R"(<(style|script|head)\b[^>]*>.*?</\1\s*>)",QRegularExpression::CaseInsensitiveOption|QRegularExpression::DotMatchesEverythingOption));
 QRegularExpression tags(R"re(<\s*(/?)\s*([a-zA-Z][a-zA-Z0-9:-]*)\b(?:[^>"']|"[^"]*"|'[^']*')*>)re");
 QString clean;qsizetype offset=0;auto matches=tags.globalMatch(text);
 const QStringList blocks={"p","div","br","ul","ol","li","blockquote","pre","table","tr","td","th"};
 while(matches.hasNext()){auto m=matches.next();clean+=text.mid(offset,m.capturedStart()-offset);QString name=m.captured(2).toLower();if(blocks.contains(name))clean+="<"+m.captured(1)+name+">";else if(QRegularExpression("^h[1-6]$").match(name).hasMatch())clean+="<"+m.captured(1)+"p>";offset=m.capturedEnd();}
 clean+=text.mid(offset);QTextDocument d;d.setHtml(clean);return d.toPlainText();
}
}
QStringList GoogleClient::scopes(){return {"https://www.googleapis.com/auth/gmail.readonly","https://www.googleapis.com/auth/calendar.readonly"};}
QString GoogleClient::challenge(const QString&v){return QCryptographicHash::hash(v.toLatin1(),QCryptographicHash::Sha256).toBase64(QByteArray::Base64UrlEncoding|QByteArray::OmitTrailingEquals);}
QJsonObject GoogleClient::parseClient(const QByteArray&json,QString*error){if(error)error->clear();auto o=QJsonDocument::fromJson(json).object()["installed"].toObject();if(!o["client_id"].toString().endsWith(".apps.googleusercontent.com")){if(error)*error="Choose the downloaded JSON for a Google OAuth Desktop app client.";return {};}return o;}
bool GoogleClient::configure(const QByteArray&json,QString*error){auto o=parseClient(json,error);if(o.isEmpty())return false;clientId=o["client_id"].toString();clientSecret=o["client_secret"].toString();return true;}
bool GoogleClient::validCallback(const QByteArray&bytes,const QString&expected,QUrl*result){auto line=bytes.split('\n').value(0).trimmed().split(' ');if(line.size()!=3||line[0]!="GET")return false;QUrl url=QUrl::fromEncoded(line[1]);QUrlQuery q(url);if(url.path()!="/oauth/callback"||q.allQueryItemValues("state").size()!=1||expected.isEmpty())return false;auto a=q.queryItemValue("state").toUtf8(),b=expected.toUtf8();if(a.size()!=b.size())return false;unsigned char diff=0;for(int i=0;i<a.size();++i)diff|=static_cast<unsigned char>(a[i]^b[i]);if(diff)return false;if(result)*result=url;return true;}
GoogleClient::GoogleClient(QObject*parent):QObject(parent),network(this),listener(this),authTimer(this){authTimer.setSingleShot(true);connect(&authTimer,&QTimer::timeout,this,[this]{listener.close();state.clear();emit problem("Google sign-in timed out. Please try again.");});connect(&listener,&QTcpServer::newConnection,this,[this]{while(listener.hasPendingConnections()){auto*s=listener.nextPendingConnection();auto*timeout=new QTimer(s);timeout->setSingleShot(true);connect(timeout,&QTimer::timeout,s,&QTcpSocket::disconnectFromHost);timeout->start(5000);connect(s,&QTcpSocket::disconnected,s,&QObject::deleteLater);connect(s,&QTcpSocket::readyRead,this,[this,s]{auto bytes=s->property("request").toByteArray()+s->readAll();if(bytes.size()>16384){s->disconnectFromHost();return;}s->setProperty("request",bytes);if(!bytes.contains("\r\n\r\n"))return;QUrl callback;bool valid=!exchanging&&validCallback(bytes,state,&callback);QByteArray response=valid?"Return to Omadash to finish connecting.":"Invalid sign-in response. Return to Omadash.";s->write("HTTP/1.1 "+QByteArray(valid?"200 OK":"400 Bad Request")+"\r\nContent-Type: text/plain; charset=utf-8\r\nCache-Control: no-store\r\nConnection: close\r\nContent-Length: "+QByteArray::number(response.size())+"\r\n\r\n"+response);s->disconnectFromHost();if(!valid)return;listener.close();authTimer.stop();state.clear();QUrlQuery q(callback);if(q.hasQueryItem("error")||q.queryItemValue("code").isEmpty()){emit problem("Google access was not granted.");return;}exchanging=true;token({{"code",q.queryItemValue("code",QUrl::FullyDecoded)},{"code_verifier",verifier},{"redirect_uri",redirect},{"grant_type","authorization_code"}},[this](QJsonObject data,QString error){exchanging=false;verifier.clear();if(!error.isEmpty()){emit problem(error);return;}auto granted=data["scope"].toString().split(' ');for(const auto&s:scopes())if(!granted.contains(s)&&!(s.endsWith("gmail.readonly")&&granted.contains("https://www.googleapis.com/auth/gmail.modify"))){disconnectAccount();emit problem("Both Gmail and Calendar read-only access are required. Please reconnect and select both permissions.");return;}emit authorized();});});}});}
void GoogleClient::authorize(bool modify,const QString&hint){if(clientId.isEmpty()){emit problem("Import the Google Desktop client JSON first.");return;}if(listener.isListening()||exchanging){emit progress("Finish the Google sign-in already open in your browser.");return;}if(!listener.listen(QHostAddress::LocalHost,0)){emit problem("Could not open the local sign-in callback.");return;}state=randomString();verifier=randomString();redirect=QString("http://127.0.0.1:%1/oauth/callback").arg(listener.serverPort());QUrl u("https://accounts.google.com/o/oauth2/v2/auth");QUrlQuery q;for(auto p:QList<QPair<QString,QString>>{{"client_id",clientId},{"redirect_uri",redirect},{"response_type","code"},{"scope",scopes().join(' ')+(modify?" https://www.googleapis.com/auth/gmail.modify":"")},{"state",state},{"code_challenge",challenge(verifier)},{"code_challenge_method","S256"},{"access_type","offline"},{"prompt","consent select_account"}})q.addQueryItem(p.first,p.second);if(!hint.isEmpty())q.addQueryItem("login_hint",hint);u.setQuery(q);authorizationUrl=u;authTimer.start(180000);emit signInReady(u);if(!QDesktopServices::openUrl(u)){emit progress("Browser could not open. Use Copy sign-in link and paste it in your browser.");return;}emit progress("Waiting for Google sign-in. If no browser appears, use Copy sign-in link.");}

void GoogleClient::disconnectAccount(){++generation;listener.close();authTimer.stop();accessToken.clear();refreshToken.clear();state.clear();verifier.clear();authorizationUrl.clear();expires={};exchanging=false;modifyGranted=false;}
void GoogleClient::token(const QList<QPair<QString,QString>>&fields,Done done){QUrlQuery q;for(auto p:fields)q.addQueryItem(p.first,p.second);q.addQueryItem("client_id",clientId);if(!clientSecret.isEmpty())q.addQueryItem("client_secret",clientSecret);QNetworkRequest r(QUrl("https://oauth2.googleapis.com/token"));r.setHeader(QNetworkRequest::ContentTypeHeader,"application/x-www-form-urlencoded");r.setTransferTimeout(20000);r.setAttribute(QNetworkRequest::RedirectPolicyAttribute,QNetworkRequest::ManualRedirectPolicy);auto*reply=network.post(r,([&]{QByteArray form;for(auto p:q.queryItems(QUrl::FullyDecoded)){if(!form.isEmpty())form.append('&');form.append(QUrl::toPercentEncoding(p.first));form.append('=');form.append(QUrl::toPercentEncoding(p.second));}return form;})());int gen=generation;connect(reply,&QNetworkReply::finished,this,[this,reply,done,gen]{auto bytes=reply->readAll();auto data=QJsonDocument::fromJson(bytes).object();bool ok=reply->error()==QNetworkReply::NoError&&reply->attribute(QNetworkRequest::HttpStatusCodeAttribute).toInt()==200;reply->deleteLater();if(gen!=generation)return;if(!ok||data["access_token"].toString().isEmpty()){done({},"Google sign-in or token renewal failed. Reconnect the account and check the app's Google Cloud setup.");return;}if(data.contains("scope"))modifyGranted=data["scope"].toString().split(' ').contains("https://www.googleapis.com/auth/gmail.modify");accessToken=data["access_token"].toString();if(!data["refresh_token"].toString().isEmpty()){refreshToken=data["refresh_token"].toString();emit credentialsChanged();}expires=QDateTime::currentDateTimeUtc().addSecs(data["expires_in"].toInt(3600)-60);done(data,{});});}
void GoogleClient::get(const QString&path,const QList<QPair<QString,QString>>&params,Done done){ensureToken([this,path,params,done](QJsonObject,QString error){if(!error.isEmpty())done({},error);else request(path,params,done);});}
void GoogleClient::request(const QString&path,const QList<QPair<QString,QString>>&params,Done done,bool retry){if(!path.startsWith("gmail/v1/users/me/")&&!path.startsWith("calendar/v3/")){done({},"Unsupported Google resource.");return;}QUrl url("https://www.googleapis.com/"+path);QUrlQuery q;for(auto p:params)if(!p.second.isEmpty())q.addQueryItem(p.first,p.second);url.setQuery(q);QNetworkRequest r(url);r.setRawHeader("Authorization","Bearer "+accessToken.toUtf8());r.setTransferTimeout(20000);r.setAttribute(QNetworkRequest::RedirectPolicyAttribute,QNetworkRequest::ManualRedirectPolicy);auto*reply=network.get(r);int gen=generation;connect(reply,&QNetworkReply::finished,this,[this,reply,path,params,done,retry,gen]{int status=reply->attribute(QNetworkRequest::HttpStatusCodeAttribute).toInt();bool ok=reply->error()==QNetworkReply::NoError;auto data=QJsonDocument::fromJson(reply->readAll()).object();reply->deleteLater();if(gen!=generation)return;if(status==401&&retry&&!refreshToken.isEmpty()){token({{"grant_type","refresh_token"},{"refresh_token",refreshToken}},[this,path,params,done](QJsonObject,QString e){if(!e.isEmpty())done({},e);else request(path,params,done,false);});return;}if(!ok||status!=200){done(QJsonObject{{"_httpStatus",status}},status==401?"Your Google session expired. Reconnect the account.":status==403?"Google denied access. Check granted permissions and enable Gmail and Calendar APIs in the project.":status==429?"Google is limiting requests. Wait briefly, then refresh.":"Could not load Google data. Check your connection and try again.");return;}done(data,{});});}
QJsonObject GoogleClient::normalizeThread(const QJsonObject&data,const QString&account){QJsonArray messages;QStringList labels;QList<QJsonObject> sorted;for(auto v:data["messages"].toArray())sorted<<v.toObject();std::stable_sort(sorted.begin(),sorted.end(),[](auto a,auto b){return a["internalDate"].toString().toLongLong()<b["internalDate"].toString().toLongLong();});for(auto m:sorted){auto p=m["payload"].toObject();for(auto v:m["labelIds"].toArray())if(!labels.contains(v.toString()))labels<<v.toString();QJsonArray resources;assets(p,resources);QString text=body(p,"text/plain");if(text.isEmpty())text=plain(body(p,"text/html"));if(text.isEmpty())text="No readable message body available in this copy.";QString from=header(p,"From"),sender=from.section('<',0,0).trimmed();if(sender.isEmpty())sender=email(from);QString date=header(p,"Date");auto dt=QDateTime::fromString(date,Qt::RFC2822Date);if(!dt.isValid())dt=QDateTime::fromMSecsSinceEpoch(m["internalDate"].toString().toLongLong(),QTimeZone::UTC);messages.append(QJsonObject{{"id",m["id"]},{"labelIds",m["labelIds"]},{"sender",sender},{"from",from},{"fromEmail",email(from)},{"replyTo",email(header(p,"Reply-To"))},{"to",addresses(header(p,"To"))},{"cc",addresses(header(p,"Cc"))},{"bcc",header(p,"Bcc").isEmpty()?QJsonValue(QJsonValue::Null):QJsonValue(addresses(header(p,"Bcc")))},{"date",dt.toString(Qt::ISODate)},{"originalDate",date},{"messageId",header(p,"Message-ID")},{"body",text},{"html",body(p,"text/html")},{"assets",resources},{"attachments",Attachments::collect(p)}});}
 if(messages.isEmpty())return {};auto last=messages.last().toObject();QJsonArray tags;for(auto name:labels)tags.append(name.toLower());bool cal=false,docs=false;for(auto m:sorted){auto p=m["payload"].toObject();QString h=header(p,"Content-Type")+header(p,"Subject");if(h.contains("text/calendar",Qt::CaseInsensitive))cal=true;QString from=header(p,"From");if(from.contains("calendar-notification@google.com"))cal=true;if(from.contains("drive-shares")||from.contains("comments-noreply@docs.google.com"))docs=true;}if(cal)tags.append("calendar");if(docs)tags.append("docs");auto dt=QDateTime::fromString(last["date"].toString(),Qt::ISODate).toLocalTime();return {{"id",data["id"]},{"historyId",data["historyId"]},{"account",account},{"sender",last["sender"]},{"email",last["fromEmail"]},{"subject",header(sorted.first()["payload"].toObject(),"Subject")},{"snippet",plain(data["snippet"].toString())},{"date",dt.toString(Qt::ISODate)},{"time",dt.date()==QDate::currentDate()?dt.toString("HH:mm"):dt.toString("MMM d")},{"messages",messages},{"labels",tags},{"unread",labels.contains("UNREAD")},{"starred",labels.contains("STARRED")},{"archived",!labels.contains("INBOX")},{"trash",labels.contains("TRASH")}};}

void GoogleClient::setThreadUnread(const QString&id,bool unread,Done done){if(!modifyGranted){done({},"Reconnect with Gmail modification permission first.");return;}get("gmail/v1/users/me/profile",{},[this,id,unread,done](QJsonObject,QString error){if(!error.isEmpty()){done({},error);return;}QNetworkRequest r(QUrl("https://www.googleapis.com/gmail/v1/users/me/threads/"+QString::fromLatin1(QUrl::toPercentEncoding(id))+"/modify"));r.setRawHeader("Authorization","Bearer "+accessToken.toUtf8());r.setHeader(QNetworkRequest::ContentTypeHeader,"application/json");r.setTransferTimeout(20000);r.setAttribute(QNetworkRequest::RedirectPolicyAttribute,QNetworkRequest::ManualRedirectPolicy);auto*reply=network.post(r,QJsonDocument(QJsonObject{{unread?"addLabelIds":"removeLabelIds",QJsonArray{"UNREAD"}}}).toJson(QJsonDocument::Compact));int gen=generation;connect(reply,&QNetworkReply::finished,this,[this,reply,gen,done]{bool ok=reply->error()==QNetworkReply::NoError&&reply->attribute(QNetworkRequest::HttpStatusCodeAttribute).toInt()==200;auto result=QJsonDocument::fromJson(reply->readAll()).object();reply->deleteLater();if(gen!=generation)return;done(result,ok?QString():"Gmail could not update read status. No local change was applied; refresh to check Gmail.");});});}

QByteArray GoogleClient::credentials()const{return refreshToken.isEmpty()?QByteArray():QJsonDocument(QJsonObject{{"refresh_token",refreshToken},{"modify",modifyGranted}}).toJson(QJsonDocument::Compact);}
bool GoogleClient::restoreCredentials(const QByteArray&bytes){auto o=QJsonDocument::fromJson(bytes).object();if(o["refresh_token"].toString().isEmpty())return false;refreshToken=o["refresh_token"].toString();modifyGranted=o["modify"].toBool();expires={};return true;}
void GoogleClient::ensureToken(Done done){if(!accessToken.isEmpty()&&expires>QDateTime::currentDateTimeUtc()){done({},{});return;}if(refreshToken.isEmpty()){done({},"Reconnect this Google account.");return;}renewWaiters<<done;if(renewing)return;renewing=true;token({{"grant_type","refresh_token"},{"refresh_token",refreshToken}},[this](QJsonObject,QString error){renewing=false;auto waiting=renewWaiters;renewWaiters.clear();for(auto fn:waiting)fn({},error);});}
void GoogleClient::mutate(const QString&method,const QString&path,const QJsonObject&body,Done done){if(!modifyGranted){done({},"Enable Gmail actions for this account first.");return;}if(!path.startsWith("gmail/v1/users/me/")||!QStringList{"POST","PUT","DELETE"}.contains(method)){done({},"Unsupported Gmail action.");return;}ensureToken([this,method,path,body,done](QJsonObject,QString error){if(!error.isEmpty()){done({},error);return;}if(!modifyGranted){done({},"Google has not granted sending permission. Open Accounts → Enable Gmail actions.");return;}QNetworkRequest r(QUrl("https://www.googleapis.com/"+path));r.setRawHeader("Authorization","Bearer "+accessToken.toUtf8());r.setHeader(QNetworkRequest::ContentTypeHeader,"application/json");r.setTransferTimeout(30000);r.setAttribute(QNetworkRequest::RedirectPolicyAttribute,QNetworkRequest::ManualRedirectPolicy);auto*reply=network.sendCustomRequest(r,method.toLatin1(),QJsonDocument(body).toJson(QJsonDocument::Compact));int gen=generation;connect(reply,&QNetworkReply::finished,this,[this,reply,gen,done]{int status=reply->attribute(QNetworkRequest::HttpStatusCodeAttribute).toInt();auto data=QJsonDocument::fromJson(reply->readAll()).object();bool ok=reply->error()==QNetworkReply::NoError&&status>=200&&status<300;reply->deleteLater();if(gen!=generation)return;if(!ok){data["_httpStatus"]=status;data["_uncertain"]=status==0||status>=500;done(data,actionError(status,data));return;}done(data,{});});});}

QString GoogleClient::actionError(int status,const QJsonObject& response) {
 const auto error=response["error"].toObject();
 QStringList reasons;
 for(const auto& v:error["errors"].toArray()) reasons<<v.toObject()["reason"].toString();
 for(const auto& v:error["details"].toArray()) reasons<<v.toObject()["reason"].toString();
 if(status==401) return "Your Google session expired. Reconnect current account permissions in Accounts.";
 if(status==403) {
  if(reasons.contains("insufficientPermissions")||reasons.contains("ACCESS_TOKEN_SCOPE_INSUFFICIENT")) return "Google has not granted sending permission. Open Accounts → Reconnect current account permissions, and approve Gmail read, compose, and send access.";
  if(reasons.contains("domainPolicy")) return "Your Google Workspace policy blocks this action. Ask the Workspace administrator to allow Omadash Gmail access.";
  if(reasons.contains("rateLimitExceeded")||reasons.contains("userRateLimitExceeded")||reasons.contains("dailyLimitExceeded")) return "Google's request or daily limit was reached. Wait before trying again; reconnecting will not reset the limit.";
  if(reasons.contains("accessNotConfigured")||reasons.contains("SERVICE_DISABLED")) return "The Gmail API is disabled for this Google Cloud project. Enable it in Google Cloud Console.";
 }
 if(status==429) return "Google is limiting requests. Wait before trying again.";
 if(status==400) return "Google rejected the draft's format or recipients. Check the addresses and try again.";
 if(status==403) {
  QString reason=reasons.join(", ");reason.remove(QRegularExpression("[^A-Za-z0-9_, -]"));
  return "Google denied the action (403"+(reason.isEmpty()?QString():"; "+reason.left(100))+"). Your account may have a permission or policy restriction.";
 }
 return "Gmail could not confirm this action. Check Gmail before retrying.";
}
