#include "mailstore.h"
#include <QFile>
#include <QSaveFile>
#include <QJsonDocument>
#include <QCoreApplication>
#include <QDir>
#include <QRegularExpression>
static void initResources(){Q_INIT_RESOURCE(fixtures);}
MailStore::MailStore(bool persist):persistent(persist){initResources();QFile f(":/src/sample.json");if(!f.open(QIODevice::ReadOnly))qFatal("Missing sample resource");auto data=QJsonDocument::fromJson(f.readAll()).object();accounts=data["accounts"].toArray();splits=data["splits"].toArray();threads=data["threads"].toArray();if(persistent){QFile saved(QCoreApplication::applicationDirPath()+"/../.state/workspace.json");if(saved.open(QIODevice::ReadOnly)){auto o=QJsonDocument::fromJson(saved.readAll()).object();if(o["schema"].toInt()==1){threads=o["threads"].toArray();splits=o["splits"].toArray();drafts=o["drafts"].toObject();}}}}
QString MailStore::accountEmail(const QString&id)const{for(auto a:accounts)if(a.toObject()["id"].toString()==id)return a.toObject()["email"].toString();return {};}
bool MailStore::matches(const QJsonObject&t,const QString&q,QString*error)const{
 if(error)error->clear();if(q.count('"')%2){if(error)*error="Close the quotation mark to finish the search.";return false;}
 QRegularExpression re(R"((?:[^\s"]|"[^"]*")+)" );auto it=re.globalMatch(q);bool all=true;
 while(it.hasNext()){QString token=it.next().captured();token.remove('"');bool neg=token.startsWith('-');if(neg)token.remove(0,1);QString f=token.section(':',0,0).toLower(),v=token.section(':',1).toLower();bool result=false;
 auto contains=[&](QString text){return text.contains(v,Qt::CaseInsensitive);};
 if(token.contains(':')){if(v.isEmpty()){if(error)*error="Add a value after "+f+":";return false;}
 if(f=="from")result=contains(t["sender"].toString()+" "+t["email"].toString());else if(f=="to")result=contains(accountEmail(t["account"].toString()));else if(f=="subject")result=contains(t["subject"].toString());else if(f=="account")result=contains(t["account"].toString()+" "+accountEmail(t["account"].toString()));else if(f=="label"){for(auto l:t["labels"].toArray())if(l.toString().compare(v,Qt::CaseInsensitive)==0)result=true;}
 else if(f=="is"){if(v=="unread")result=t["unread"].toBool();else if(v=="read")result=!t["unread"].toBool();else if(v=="starred")result=t["starred"].toBool();else{if(error)*error="Use is:unread, is:read, or is:starred.";return false;}}
 else if(f=="before"||f=="after"){if(!QRegularExpression("^\\d{4}-\\d{2}-\\d{2}$").match(v).hasMatch()){if(error)*error="Use a date such as before:2022-01-01.";return false;}result=f=="before"?t["date"].toString()<v:t["date"].toString()>v;}
 else{if(error)*error="Unsupported preview filter: "+f;return false;}}
 else{QString hay=t["sender"].toString()+t["subject"].toString()+t["snippet"].toString();for(auto m:t["messages"].toArray())hay+=m.toObject()["body"].toString();result=hay.contains(token,Qt::CaseInsensitive);}all&=neg?!result:result;
 }return all;
}
QString MailStore::matchingSplit(const QJsonObject&t)const{for(auto s:splits){auto o=s.toObject();if(o["id"]=="other"||matches(t,o["rule"].toString()))return o["id"].toString();}return "other";}
QVector<int> MailStore::visible(const QString&a,const QString&s,const QString&v,const QString&q,QString*err)const{QVector<int> rows;if(err)err->clear();if(v=="search"){QString error;matches(threads.first().toObject(),q,&error);if(!error.isEmpty()){if(err)*err=error;return rows;}}for(int i=0;i<threads.size();++i){auto t=threads[i].toObject();if(a!="all"&&t["account"].toString()!=a)continue;if(v=="trash"){if(t["trash"].toBool())rows<<i;continue;}if(t["trash"].toBool())continue;bool show=v=="all"||(v=="search"&&matches(t,q))||(v=="archive"&&t["archived"].toBool())||(v=="starred"&&t["starred"].toBool())||(v=="inbox"&&!t["archived"].toBool()&&matchingSplit(t)==s);if(show)rows<<i;}return rows;}
QJsonObject MailStore::replyDraft(int tIndex,int mIndex,const QString&mode)const{auto t=threads[tIndex].toObject(),m=t["messages"].toArray()[mIndex].toObject();QString own=accountEmail(t["account"].toString());QStringList to,cc,identities;for(auto a:accounts)identities<<a.toObject()["email"].toString();auto add=[&](QStringList&list,const QString&e){if(!e.isEmpty()&&!identities.contains(e,Qt::CaseInsensitive)&&!list.contains(e,Qt::CaseInsensitive))list<<e;};if(mode!="forward"){add(to,m["replyTo"].toString().isEmpty()?m["fromEmail"].toString():m["replyTo"].toString());if(mode=="reply-all"||m["fromEmail"].toString()==own)for(auto v:m["to"].toArray())add(to,v.toString());if(mode=="reply-all")for(auto v:m["cc"].toArray())if(!to.contains(v.toString(),Qt::CaseInsensitive))add(cc,v.toString());}
 QString subject=t["subject"].toString();subject.remove(QRegularExpression("^(Re:|Fwd:)\\s*",QRegularExpression::CaseInsensitiveOption));return {{"account",t["account"]},{"to",to.join(", ")},{"cc",cc.join(", ")},{"bcc",""},{"subject",(mode=="forward"?"Fwd: ":"Re: ")+subject},{"body",mode=="forward"?"\n\n—— Forwarded sample message ——\nFrom: "+m["from"].toString()+"\nDate: "+m["date"].toString()+"\n\n"+m["body"].toString():""},{"sourceThread",tIndex},{"sourceMessage",mIndex},{"sourceId",m["messageId"]},{"mode",mode}};}
void MailStore::change(const QVector<int>&ids,const QString&action){history<<threads;for(auto i:ids){if(i<0||i>=threads.size())continue;auto t=threads[i].toObject();if(action=="archive")t["archived"]=true;else if(action=="trash")t["trash"]=true;else if(action=="restore"){t["archived"]=false;t["trash"]=false;}else if(action=="unread")t["unread"]=!t["unread"].toBool();else if(action=="star")t["starred"]=!t["starred"].toBool();threads[i]=t;}save();}
bool MailStore::undo(){if(history.isEmpty())return false;threads=history.takeLast();save();return true;}
bool MailStore::save(){saveError.clear();if(!persistent||sessionOnly)return true;QString dir=QCoreApplication::applicationDirPath()+"/../.state";if(!QDir().mkpath(dir)){saveError="Could not create the local workspace folder.";return false;}QSaveFile f(dir+"/workspace.json");if(!f.open(QIODevice::WriteOnly)){saveError="Could not save your local workspace.";return false;}f.write(QJsonDocument(QJsonObject{{"schema",1},{"threads",threads},{"splits",splits},{"drafts",drafts}}).toJson());if(!f.commit()){saveError="Could not finish saving your local workspace.";return false;}return true;}
