#include "mailsync.h"
#include <memory>
MailSync::MailSync(GoogleClient*c,LocalCache*d,const QString&a,QObject*p):QObject(p),client(c),cache(d),account(a){timer.setInterval(60000);connect(&timer,&QTimer::timeout,this,&MailSync::refresh);}
void MailSync::start(){timer.start();QTimer::singleShot(0,this,&MailSync::refresh);}
void MailSync::refresh(){if(busy)return;busy=true;if(cache->meta(account,"baseline")!="complete")baseline();else history();}
void MailSync::finish(bool ok){busy=false;if(ok)emit updated(account);}
void MailSync::fetch(const QStringList&ids,std::function<void(bool)>done){struct Batch{int next=0,active=0;bool ok=true;};auto state=std::make_shared<Batch>();auto pump=std::make_shared<std::function<void()>>();std::weak_ptr<std::function<void()>> weak=pump;*pump=[this,ids,state,done,weak]{auto keep=weak.lock();if(!keep)return;if(state->next>=ids.size()&&state->active==0){done(state->ok);return;}while(state->active<4&&state->next<ids.size()){QString id=ids[state->next++];++state->active;client->get("gmail/v1/users/me/threads/"+QString::fromLatin1(QUrl::toPercentEncoding(id)),{{"format","full"}},[this,id,state,keep](QJsonObject data,QString error){--state->active;if(error.isEmpty()){auto thread=GoogleClient::normalizeThread(data,account);if(!thread.isEmpty()&&!cache->putThread(account,thread))state->ok=false;}else if(data["_httpStatus"].toInt()==404)cache->removeThread(account,id);else state->ok=false;(*keep)();});}};(*pump)();}
void MailSync::baseline(){QString checkpoint=cache->meta(account,"history");if(checkpoint.isEmpty()){client->get("gmail/v1/users/me/profile",{},[this](QJsonObject p,QString error){if(!error.isEmpty()){emit progress(account,error);finish(false);return;}cache->setMeta(account,"history",p["historyId"].toString());baseline();});return;}QString page=cache->meta(account,"page");emit progress(account,"Indexing mail history in the background…");client->get("gmail/v1/users/me/threads",{{"maxResults","100"},{"pageToken",page},{"includeSpamTrash","true"}},[this](QJsonObject data,QString error){if(!error.isEmpty()){if(data["_httpStatus"].toInt()==400){cache->setMeta(account,"page","");}emit progress(account,error);finish(false);return;}QStringList ids;for(auto v:data["threads"].toArray())ids<<v.toObject()["id"].toString();QString next=data["nextPageToken"].toString();fetch(ids,[this,next](bool ok){if(!ok){finish(false);return;}cache->setMeta(account,"page",next);emit updated(account);if(next.isEmpty()){cache->setMeta(account,"baseline","complete");history();}else QTimer::singleShot(750,this,&MailSync::baseline);});});}
void MailSync::history(){QString from=cache->meta(account,"history");auto ids=std::make_shared<QSet<QString>>();auto step=std::make_shared<std::function<void(QString)>>();std::weak_ptr<std::function<void(QString)>> weak=step;*step=[this,from,ids,weak](QString page){auto keep=weak.lock();if(!keep)return;client->get("gmail/v1/users/me/history",{{"startHistoryId",from},{"pageToken",page},{"maxResults","500"}},[this,ids,keep](QJsonObject data,QString error){if(!error.isEmpty()){if(data["_httpStatus"].toInt()==404){cache->clearThreads(account);cache->setMeta(account,"baseline","");cache->setMeta(account,"history","");cache->setMeta(account,"page","");QTimer::singleShot(0,this,&MailSync::baseline);return;}emit progress(account,error);finish(false);return;}for(auto h:data["history"].toArray()){auto item=h.toObject();for(auto m:item["messages"].toArray())ids->insert(m.toObject()["threadId"].toString());for(auto key:{"messagesAdded","messagesDeleted","labelsAdded","labelsRemoved"})for(auto m:item[key].toArray())ids->insert(m.toObject()["message"].toObject()["threadId"].toString());}QString next=data["nextPageToken"].toString();if(!next.isEmpty()){(*keep)(next);return;}ids->remove("");QString checkpoint=data["historyId"].toString();fetch(ids->values(),[this,checkpoint](bool ok){if(ok&&!checkpoint.isEmpty())cache->setMeta(account,"history",checkpoint);if(ok)emit progress(account,"Mail is up to date.");finish(ok);});});};(*step)("");}
