#include "mime.h"
#include <QJsonArray>
#include <QRegularExpression>
#include <QUuid>
#include <QDateTime>
#include <QUrl>
namespace {
QByteArray folded(const QByteArray&data){auto b=data.toBase64();QByteArray result;for(int i=0;i<b.size();i+=76)result+=b.mid(i,76)+"\r\n";return result;}
QByteArray encoded(const QString&s){QByteArray out;QString part;for(auto c:s){part+=c;if(part.toUtf8().size()>=36&&!c.isHighSurrogate()){if(!out.isEmpty())out+="\r\n ";out+="=?UTF-8?B?"+part.toUtf8().toBase64()+"?=";part.clear();}}if(!part.isEmpty()){if(!out.isEmpty())out+="\r\n ";out+="=?UTF-8?B?"+part.toUtf8().toBase64()+"?=";}return out;}
bool safe(const QString&s){return !s.contains(QRegularExpression("[\\x00-\\x1f\\x7f]"));}
bool addresses(const QString&s){if(s.trimmed().isEmpty())return true;if(!safe(s))return false;auto re=QRegularExpression(R"(^\s*(?:[^<>]*<)?[^\s<>@,]+@[^\s<>@,]+\.[^\s<>@,]+>?\s*$)");for(auto part:s.split(','))if(!re.match(part).hasMatch())return false;return true;}
}
QByteArray Mime::message(const QJsonObject&d,const QString&from,QString*error){error->clear();for(auto key:{"to","cc","bcc"})if(!addresses(d[key].toString())){*error="Check the email addresses in "+QString(key).toUpper()+".";return {};}if(!addresses(from)||from.isEmpty()||!safe(d["subject"].toString())||!safe(d["sourceId"].toString())){*error="Invalid message headers.";return {};}QByteArray result="From: "+from.toUtf8()+"\r\n";for(auto key:{"to","cc","bcc"})if(!d[key].toString().trimmed().isEmpty())result+=QByteArray(key)+": "+d[key].toString().toUtf8()+"\r\n";result+="Subject: "+encoded(d["subject"].toString())+"\r\nMIME-Version: 1.0\r\nDate: "+QDateTime::currentDateTimeUtc().toString("ddd, dd MMM yyyy HH:mm:ss +0000").toLatin1()+"\r\n";QString messageId=d["outgoingMessageId"].toString();if(messageId.isEmpty())messageId="<"+QUuid::createUuid().toString(QUuid::WithoutBraces)+"@omadash.local>";if(!safe(messageId)){*error="Invalid message identifier.";return {};}result+="Message-ID: "+messageId.toUtf8()+"\r\n";if(d["mode"]!="forward"&&!d["sourceId"].toString().isEmpty())result+="In-Reply-To: "+d["sourceId"].toString().toUtf8()+"\r\nReferences: "+d["sourceId"].toString().toUtf8()+"\r\n";auto files=d["attachments"].toArray();QString boundary="omadash_"+QUuid::createUuid().toString(QUuid::WithoutBraces);if(!files.isEmpty())result+="Content-Type: multipart/mixed; boundary=\""+boundary.toLatin1()+"\"\r\n\r\n--"+boundary.toLatin1()+"\r\n";result+="Content-Type: text/plain; charset=UTF-8\r\nContent-Transfer-Encoding: base64\r\n\r\n"+folded(d["body"].toString().toUtf8());qint64 total=0;for(auto value:files){auto f=value.toObject();auto data=QByteArray::fromBase64(f["data"].toString().toLatin1());total+=data.size();if(total>18*1024*1024){*error="Attachments must total less than 18 MB.";return {};}QString name=f["name"].toString(),mime=f["mime"].toString("application/octet-stream");if(!safe(name)||!QRegularExpression("^[a-zA-Z0-9.+-]+/[a-zA-Z0-9.+-]+$").match(mime).hasMatch()){*error="Invalid attachment metadata.";return {};}result+="\r\n--"+boundary.toLatin1()+"\r\nContent-Type: "+mime.toLatin1()+"\r\nContent-Disposition: attachment; filename*=UTF-8''"+QUrl::toPercentEncoding(name)+"\r\nContent-Transfer-Encoding: base64\r\n\r\n"+folded(data);}if(!files.isEmpty())result+="\r\n--"+boundary.toLatin1()+"--\r\n";if(result.size()>30*1024*1024){*error="This message is too large to send.";return {};}return result;}
